services:
  - type: web
    name: cosmic-teams
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: RENDER
        value: true 