services:
  - type: web
    name: cosmic-teams
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: RENDER
        value: true
    disk:
      name: cosmic-teams-data
      mountPath: /data
      sizeGB: 1 